FYAdmin/urls.py
# coding=utf-8
# Date: 14/11/21
# Time: 09:11
# Email:fanjunwei003@163.com
from django.conf.urls import patterns, url
from views import *

__author__ = u'范俊伟'

urlpatterns = patterns('fyadmin',
                       url(r'^img_code/$', get_img_code, name='img_code'),
                       url(r'^trading_limit/$', trading_limit, name='trading_limit'),
                       url(r'^register/$', RegisterView.as_view(), name='register'),
                       url(r'^logout/$', logout, name='logout'),
                       url(r'^$', HomeView.as_view(), name='home'),
                       url(r'^change_password/$', ChangePasswordView.as_view(), name='change_password'),
                       url(r'^change_fy/$', ChangeFYView.as_view(), name='change_fy'),
                       url(r'^cash_summary/$', CashSummaryView.as_view(), name='cash_summary'),
                       url(r'^pending_orders/$', PendingOrdersView.as_view(), name='pending_orders'),
                       url(r'^consolidated/$', ConsolidatedView.as_view(), name='consolidated'),
                       url(r'^money_supply/$', MoneySupplyView.as_view(), name='money_supply'),
                       url(r'^lend_order/(?P<goodsId>\w*?)$', LendingOrderView.as_view(), name='lend_order'),
                       url(r'^task_edit/$', TaskEditView.as_view(), name='task_edit'),
                       url(r'^task_log_list/$', TaskLogListView.as_view(), name='task_log_list'),
)

FjwDJ/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'FjwDJ.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^fy/', include('fy.urls',namespace='fy')),
    url(r'^weixin/', include('weixin.urls',namespace='weixin')),
    url(r'^$', 'fy.views.home', name='home'),
    url(r'^fyadmin/', include('FYAdmin.urls',namespace='fyadmin')),
    url(r'^android/', include('android.urls',namespace='android')),
)

fy/urls.py
__author__ = 'fanjunwei003'
from django.conf.urls import patterns, include, url
from views import *
from django.contrib import admin

urlpatterns = patterns('fy',
    # Examples:
    # url(r'^$', 'FjwDJ.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^moneySupply/$', moneySupply,name='moneySupply'),
)

FYAdmin/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.core.signing import Signer
from util.rc4 import RC4


class FYUserProfile(models.Model):
    key = 'sdfcs32vader32cvxae3v>sdcSD#2dvcs'
    user = models.OneToOneField(User)
    fy_username = models.CharField(unique=True, max_length=255, verbose_name=u'泛亚账号')
    fy_password = models.CharField(max_length=255, verbose_name=u'泛亚密码')
    enable_task = models.BooleanField(default=False, verbose_name=u'启用自动资金受托')
    goodsId_list = models.CharField(max_length=255, null=True, blank=True)
    mini_count = models.IntegerField(verbose_name=u'最少购买量', default=3)

    def get_fy_username(self):
        rc4 = RC4(key=self.key)
        return rc4.decry(self.fy_username)

    def set_fy_username(self, value):
        rc4 = RC4(key=self.key)
        self.fy_username = rc4.crypt(value)

    def get_fy_password(self):
        rc4 = RC4(key=self.key)
        return rc4.decry(self.fy_password)

    def set_fy_password(self, value):
        rc4 = RC4(key=self.key)
        self.fy_password = rc4.crypt(value)


class TaskLog(models.Model):
    user = models.ForeignKey(User)
    time = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField()
    goodsId = models.CharField(max_length=10, null=True)
    count = models.IntegerField(null=True)
    message = models.CharField(max_length=255, null=True)

FYAdmin/views.py
# coding=utf-8
# Date: 14/11/30
# Time: 19:20
# Email:fanjunwei003@163.com

import base64
from functools import update_wrapper
import os
import random
from django import http
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.utils.decorators import classonlymethod
from django.utils.html import escape, format_html
from django.utils.safestring import mark_safe
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
import time
from FYAdmin.forms import *
from FYAdmin.models import *
from django.utils.http import urlencode
from util.tools import *

__author__ = u'范俊伟'

DOT = '.'
PREVIOUS_PAGE = '<'
NEXT_PAGE = '>'


def get_img_code(request):
    string = '12345679ACEFGHKMNPRTUVWXY'
    ImageCode_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'tools', 'ImageCode.jar').replace('\\',
                                                                                                                '/')
    code = ''.join(random.sample(string, 4))
    request.session['login_img_code'] = code.lower()
    res = os.popen('java -jar ' + ImageCode_path + ' ' + code)
    data = base64.decodestring(res.read())
    return HttpResponse(data, 'image/png')


tradingLimitLock = threading.RLock()


def trading_limit(request):
    tradingLimitLock.acquire()
    try:
        goodsID = request.REQUEST.get('id')
        if hasattr(request.user, 'fyuserprofile'):
            checked, res = fy_api.trading_limit(request.user.fyuserprofile.get_fy_username(),
                                                request.user.fyuserprofile.get_fy_password(), goodsID)

            if checked:
                if res < 10:
                    html = format_html(u'<span style="color:red">{0}</span>', res)
                else:
                    html = format_html(u'<span>{0}</span>', res)
                return HttpResponse(html, 'text/html')
            else:
                raise Http404(res)
        else:
            raise Http404(u'未设置泛亚账户')
    finally:
        tradingLimitLock.release()


def logout(request):
    auth_logout(request)
    return http.HttpResponseRedirect(request.REQUEST.get('next', reverse('fyadmin:home')))


def admin_view_decorator(func):
    def admin_view(cls, cached=False, **kwargs):
        view = func(cls, **kwargs)

        def has_permission(request):
            if request.user.is_active:
                return True
            else:
                return False

        def inner(request, *args, **kwargs):
            if not has_permission(request) and getattr(cls, 'need_site_permission', True):
                return LoginView.as_view()(request, *args, **kwargs)
            return view(request, *args, **kwargs)

        if not cached:
            inner = never_cache(inner)
        return update_wrapper(inner, view)

    return admin_view


class BaseView(TemplateView):
    need_site_permission = True
    template_name = 'fyadmin/base.html'

    def get_context_data(self, **kwargs):
        kwargs = super(BaseView, self).get_context_data(**kwargs)
        kwargs['url'] = self.request.get_full_path()
        if hasattr(self, 'form'):
            kwargs['form'] = self.form
        return kwargs

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        qs = urlencode(p)
        if qs:
            return '?%s' % qs
        else:
            return ''

    @classonlymethod
    @admin_view_decorator
    def as_view(cls, **initkwargs):
        return super(BaseView, cls).as_view(**initkwargs)


class LoginView(BaseView):
    template_name = 'fyadmin/login.html'


    @classonlymethod
    def as_view(cls, **initkwargs):
        return super(BaseView, cls).as_view(**initkwargs)

    def post(self, request, *args, **kwargs):
        self.form = LoginForm(request=request, data=request.POST)
        if self.form.is_valid():
            auth_login(request, self.form.get_user())
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            return http.HttpResponseRedirect(request.REQUEST.get('next', request.get_full_path()))
        else:
            return self.get(request, *args, **kwargs)


class RegisterView(BaseView):
    need_site_permission = False
    template_name = 'fyadmin/register.html'


    def post(self, request, *args, **kwargs):
        self.form = RegisterForm(request=request, data=request.POST)
        if self.form.is_valid():
            self.form.save()
            return http.HttpResponseRedirect(request.REQUEST.get('next', reverse('fyadmin:home')))
        else:
            return self.get(request, *args, **kwargs)


class FrameView(BaseView):
    def get_site_menu(self):
        return [
            {'title': u'账户信息', 'menus':
                [
                    {'title': u'我的资金',
                     'icon': 'glyphicon-star',
                     'url': reverse('fyadmin:cash_summary')},
                    {'title': u'未成交查询',
                     'icon': 'glyphicon-star',
                     'url': reverse('fyadmin:pending_orders')},
                    {'title': u'交易资产汇总',
                     'icon': 'glyphicon-star',
                     'url': reverse('fyadmin:consolidated')},

                ],

            },

            {'title': u'资金受托', 'menus':
                [
                    {'title': u'资金配比',
                     'icon': 'glyphicon-star',
                     'url': reverse('fyadmin:money_supply')},
                    {'title': u'设置自动购买',
                     'icon': 'glyphicon-star',
                     'url': reverse('fyadmin:task_edit')},
                    {'title': u'自动执行日志',
                     'icon': 'glyphicon-star',
                     'url': reverse('fyadmin:task_log_list')},

                ],
            },
        ]

    def get_context_data(self, **kwargs):
        kwargs = super(FrameView, self).get_context_data(**kwargs)
        kwargs['nav_menu'] = self.get_site_menu()
        return kwargs

    template_name = 'fyadmin/frame.html'


class BaseListView(MultipleObjectMixin, FrameView):
    paginate_by = 100


    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super(BaseListView, self).get(request, *args, **kwargs)

    def get_paginator(self, queryset, per_page, orphans=0,
                      allow_empty_first_page=True, **kwargs):
        paginator = super(BaseListView, self).get_paginator(queryset, per_page, orphans=0,
                                                            allow_empty_first_page=True, **kwargs)
        page = self.kwargs.get(self.page_kwarg) or self.request.GET.get(self.page_kwarg) or 1
        try:
            page_number = int(page)
        except ValueError:
            if page == 'last':
                page_number = paginator.num_pages
            else:
                page_number = 0

        new_page_number = page_number

        if page_number < 1:
            new_page_number = 1
        elif page_number > paginator.num_pages:
            new_page_number = paginator.num_pages
        if new_page_number != page_number:
            self.kwargs[self.page_kwarg] = new_page_number
        return paginator

    def get_page_number(self, i):
        if i == PREVIOUS_PAGE:
            if self.page_num > 1:
                return mark_safe(u'<li><a href="%s">&laquo;</a></li> ' % (
                    escape(self.get_query_string({self.page_kwarg: self.page_num - 1}))))
            else:
                return mark_safe(u'<li class="disabled"><span >&laquo;</span></li> ')
        elif i == NEXT_PAGE:
            if self.page_num < self.paginator.num_pages:
                return mark_safe(u'<li><a href="%s">&raquo;</a></li> ' % (
                    escape(self.get_query_string({self.page_kwarg: self.page_num + 1}))))
            else:
                return mark_safe(u'<li class="disabled"><span >&raquo;</span></li> ')
        elif i == DOT:
            return mark_safe(u'<li><span class="dot-page">...</span></li>')
        elif i == self.page_num:
            return mark_safe(u'<li class="active"><span>%d</span></li> ' % i)
        else:
            return mark_safe(u'<li><a href="%s">%d</a></li> ' % (
                escape(self.get_query_string({self.page_kwarg: i})), i))

    def page_range(self, paginator, page_num, page_type='normal'):
        """
        Generates the series of links to the pages in a paginated list.
        """

        ON_EACH_SIDE = {'normal': 5, 'small': 3}.get(page_type, 3)
        ON_ENDS = 2
        self.paginator = paginator
        self.page_num = page_num
        total_pages_num = paginator.num_pages
        # If there are 10 or fewer pages, display links to every page.
        # Otherwise, do some fancy
        if total_pages_num <= 10:
            page_range = range(1, total_pages_num + 1)
        else:
            # Insert "smart" pagination links, so that there are always ON_ENDS
            # links at either end of the list of pages, and there are always
            # ON_EACH_SIDE links at either end of the "current page" link.
            page_range = []
            if page_num > (ON_EACH_SIDE + ON_ENDS):

FYAdmin/templates/fyadmin/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>泛亚管理-{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/3.3.1/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}fyadmin/css/base.css">
    <script src="{{ STATIC_URL }}js/jquery-1.11.1.min.js"></script>
    <script src="{{ STATIC_URL }}fyadmin/js/base.js"></script>
    <link href="{{ STATIC_URL }}jquery-ui/jquery-ui.min.css" rel="stylesheet">
    <script src="{{ STATIC_URL }}jquery-ui/jquery-ui.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="{{ STATIC_URL }}js/respond.min.js"></script>
        <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
    <![endif]-->
    <style>
        @-moz-document url-prefix() {
            fieldset {
                display: table-cell;
            }
        }
    </style>
    {% block ext_header %}{% endblock %}
</head>
<body class="{% block body-class %}{% endblock %}">
{% block body %}
{% endblock %}

<script src="{{ STATIC_URL }}bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}bootstrap/3.3.1/js/bootstrap-datetimepicker.js"></script>
<script src="{{ STATIC_URL }}bootstrap/3.3.1/js/bootstrap-datetimepicker.zh-CN.js"></script>
</body>
</html>

FYAdmin/templates/fyadmin/cash_summary.html
{% extends 'fyadmin/frame.html' %}

{% block content %}
    <div class="container-fluid">
        {% for object in object_list %}
            {% if object %}
                <div class="row">
                    <div class="col-md-6 col-xs-6 text-right">
                        {{ object.0 }}
                    </div>
                    <div class="col-md-3 col-xs-6 text-right">
                        {{ object.1 }}
                    </div>
                </div>
            {% else %}
                <br>
            {% endif %}
        {% endfor %}
    </div>


{% endblock %}

FYAdmin/templates/fyadmin/change_fy.html
{% extends 'fyadmin/frame_edit.html' %}
{% block fields %}
    {% with field=form.fy_username %}
        {% include 'fyadmin/inclute/form_field_text.html' %}
    {% endwith %}
    {% with field=form.fy_password %}
        {% include 'fyadmin/inclute/form_field_password.html' %}
    {% endwith %}
{% endblock %}
{% block buttons %}
    <button type="submit" class="btn btn-primary">修改</button>
{% endblock %}

FYAdmin/templates/fyadmin/change_password.html
{% extends 'fyadmin/frame_edit.html' %}
{% block fields %}
    {% with field=form.password_old %}
        {% include 'fyadmin/inclute/form_field_password.html' %}
    {% endwith %}
    {% with field=form.password_new1 %}
        {% include 'fyadmin/inclute/form_field_password.html' %}
    {% endwith %}
    {% with field=form.password_new2 %}
        {% include 'fyadmin/inclute/form_field_password.html' %}
    {% endwith %}
{% endblock %}
{% block buttons %}
    <button type="submit" class="btn btn-primary">修改密码</button>
{% endblock %}

FYAdmin/templates/fyadmin/frame.html
{% extends 'fyadmin/base.html' %}
{% block title %}{{ view.title }}{% endblock %}
{% block  body %}
    <!-- Frame -->
    <nav class="navbar navbar-default navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">泛亚管理</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                            <strong>欢迎， {% if user.first_name %}{{ user.first_name }}{% else %}
                                {{ user.get_username }}{% endif %}</strong> <span class="caret"></span></a>
                        <ul id="g-account-menu" class="dropdown-menu" role="menu">
                            <li>
                                <a href="{% url 'fyadmin:change_password' %}">
                                    <span class="glyphicon glyphicon-cog"></span>
                                    更改密码
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'fyadmin:change_fy' %}">
                                    <span class="glyphicon glyphicon-cog"></span>
                                    修改泛亚账号
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li><a href="{% url 'fyadmin:logout' %}"><span class="glyphicon glyphicon-log-out"></span>
                        注销</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <!-- navbar -->

    <!-- navbar end -->
    <div class=" container-fluid">
        <div class="clearfix row">
            <!-- Left menu-->
            <div id="left-side" class="col-md-2">
                {% include 'fyadmin/inclute/sitemenu.html' %}
            </div>
            <!-- Left menu end-->
            <div class="col-md-9 col-lg-10 col-sm-9 col-xs-12">
                {% if messages %}
                    {% for message in messages %}
                        {% ifequal message.tags 'error' %}
                            <div class="alert alert-danger"
                                 role="alert">{{ message }}</div>
                        {% else %}
                            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}"
                                 role="alert">{{ message }}</div>
                        {% endifequal %}
                    {% endfor %}

                {% endif %}
                {% block content-title %}
                    <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
                         data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
                         data-class-sm="navbar content-navbar navbar-default navbar-xs">
                        <div class="navbar-header">

                            <span class="navbar-brand">
                                {% if view.parents %}
                                    {% for parent in view.parents %}
                                        <span class="parent-brand"><a
                                                href="{{ parent.url }}"><u>{{ parent.name }}</u></a> <span
                                                class="glyphicon glyphicon-chevron-right"></span></span>
                                    {% endfor %}
                                {% endif %}
                                {{ view.title }}
                            </span>

                        </div>
                    </div>
                {% endblock %}

                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
    <!-- Frame end-->
{% endblock %}

FYAdmin/templates/fyadmin/frame_edit.html
{% extends 'fyadmin/frame.html' %}
{% block content %}

    <form action="" class="form-horizontal" method="post" role="form">
        <div class="form-container row">
            <div class="col-md-12 ">
                <div class="panel panel-default fieldset">
                    <div class="panel-body">
                        {% include 'fyadmin/inclute/form_non_field_errors.html' %}
                        {% block fields %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                {% block buttons %}{% endblock %}
            </div>
        </div>
    </form>
{% endblock %}

FYAdmin/templates/fyadmin/home.html
{% extends 'fyadmin/frame.html' %}
{% block content %}
    <div style="margin: auto;text-align: center">
        <iframe allowtransparency="true" frameborder="0" width="255" height="98" scrolling="no"
                src="http://tianqi.2345.com/plugin/widget/index.htm?s=1&z=1&t=1&v=0&d=1&k=&f=1&q=1&e=0&a=1&c=58362&w=255&h=98"></iframe>
    </div>
{% endblock %}

FYAdmin/templates/fyadmin/login.html
{% extends 'fyadmin/base.html' %}
{% block title %}登录{% endblock %}
{% block ext_header %}
    <style>
        #login_panel {
            box-shadow: 0 0 1em 1em #ccc;
            max-width: 350px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 50px
        }

        #img_code_view {
            cursor: pointer;
        }
    </style>
    <script>
        function change_img_code() {
            var img = $('#img_code_view');
            var rand = Math.random();
            img.attr('src', "{% url 'fyadmin:img_code' %}?t=" + rand);
        }
    </script>
{% endblock %}
{% block body %}

    <div class="container">

        <form action="" method="post" class="form">
            <div class="panel panel-default panel-single" id="login_panel">

                <div class="panel-heading">

                    <h2>泛亚管理登录</h2>
                </div>
                <div class="panel-body">
                    {% if form.non_field_errors %}
                        <div class="alert alert-block alert-danger">
                            <ul>
                                {{ form.non_field_errors|unordered_list }}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="input-group input-group-lg {% if form.username.errors %}has-error{% endif %}">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>

                            <input id="username" type="text" class="form-control  " name="username" placeholder="用户名"
                                   type="text">
                        </div>
                        {% for error in form.username.errors %}
                            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}"
                               class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        <div class="input-group input-group-lg {% if form.password.errors %}has-error{% endif %}">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>

                            <input id="password" type="password" class="form-control" name="password" placeholder="密码"
                                   type="text">
                        </div>
                        {% for error in form.password.errors %}
                            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}"
                               class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        <div class="input-group input-group-lg {% if form.img_code.errors %}has-error{% endif %}">
                            <div class="input-group-addon "><img id="img_code_view" onclick="change_img_code();"
                                                                 width="90" height="20"
                                                                 src="{% url 'fyadmin:img_code' %}"></div>
                            <input id="img_code" type="text" class="form-control" name="img_code" placeholder="验证码"
                                   type="text">


                        </div>
                        {% for error in form.img_code.errors %}
                            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}"
                               class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="提交">

                </div>

                <div class="panel-footer">
                    <!--
                    <div><a href="">忘记用户名或密码</a></div>
                    -->
                    <div><a href="{% url 'fyadmin:register' %}?next={{ url }}">注册</a></div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

FYAdmin/templates/fyadmin/money_supply.html
{% extends 'fyadmin/frame.html' %}

{% block ext_header %}
    <script src="{{ STATIC_URL }}fyadmin/js/change_list.js"></script>
    <style>
        .col-md-6 {
            font-size: 1.2em;
        }
    </style>
    <script>
        //$(function () {
        //    $('[role=trading_limit]').each(function () {
        //        var control = $(this);
        //        var goodsID = control.attr('goodsID');
        //        $.get("{% url 'fyadmin:trading_limit' %}?id=" + goodsID, function (result) {
        //            control.html(result);
        //        });
        //    });
        //});

    </script>

{% endblock %}
{% block content %}


    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover" id="object_table">
            <thead>
            <tr>
                <th>名称</th>
                <th>资金比例</th>
                <th>资金需求委托总量</th>
                <th>资金受托申报总量</th>
                <th>指导价</th>
                <th>委托受托价</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>

                    <td>
                        <a href="{% url 'fyadmin:lend_order' object.id %}">

                            {{ object.name|default_if_none:'' }}{{ object.id|default_if_none:'' }}
                        </a>
                    </td>
                    <td>
                        <div style='text-align:right;'>
                            {{ object.ratio_format|default_if_none:'' }}{% if object.ratio %}%{% endif %}</div>
                    </td>
                    <td>
                        <div style='text-align:right;'>{{ object.moneySupplyRequested|default_if_none:'' }}</div>
                    </td>
                    <td>
                        <div style='text-align:right;'>{{ object.moneySupply|default_if_none:'' }}</div>
                    </td>
                    <td>
                        <div style='text-align:right;'>{{ object.recommendation|default_if_none:'' }}</div>
                    </td>
                    <td>
                        <div style='text-align:right;'>{{ object.financePrice|default_if_none:'' }}</div>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="modal  fade" id="delModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">取消</span></button>
                    <h4 class="modal-title">确认撤销</h4>
                </div>
                <div class="modal-body">
                    <p>您确认要撤销所选吗?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" name="__action_delete" class="btn btn-danger">确定</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
{% endblock %}